DEV - Update appveyor
1, Disable appveyor vs2013 build due to glog v0.3.5 compiler error C2483.
2, use configuration matrix
3, add RDP option.

Use LocalAppVeyor for linting.